#
# **This is an example configuration file. Uncomment the lines that need to be enabled.**
#
#
ServiceKey: your_service_key:your_service_name  # - env var: APPOPTICS_SERVICE_KEY
# Sampling:
#   TracingMode: enabled  # - env var: APPOPTICS_TRACING_MODE
# PrependDomain: true  # - env var: APPOPTICS_PREPEND_DOMAIN
# HostAlias: my-alias  # - env var: APPOPTICS_HOSTNAME_ALIAS
# SQLSanitize: 2  # - env var: APPOPTICS_SQL_SANITIZE
# TransactionSettings:
# - Type: url
#   RegEx: \s+\d+\s+
#   Tracing: disabled
# - Type: url
#   Extensions:
#   - .jpg
#   Tracing: disabled
# Disabled: false  # - env var: APPOPTICS_DISABLED
# DebugLevel: warn  # - env var: APPOPTICS_DEBUG_LEVEL
